version: "3.8"
services:
  a-db:
    image: "postgres:14.1-alpine"
    restart: always
    container_name: "postgres-assigment-container"
    ports:
      - 5432:5432
    volumes:
      - a-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres-assigment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  a-backend:
    image: 'springboot_doc_assigment:latest'
    build:
      context: ./
    container_name: 'springboot_assigment_container'
    ports:
      - 8080:8080
    depends_on:
      - a-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres-assigment
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  a-db-data:
    driver: local