spring.application.name=springbootdocassigment
spring.datasource.url=jdbc:postgresql://db:5432/postgres-assigment
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update